name: Upload Carthage Artifact

on:
  push:
    branches: [ fix-carthage-upload-script ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: "🚀 Upload Carthage Artifact"
    runs-on: macos-latest
    steps:
      - name: "Check-out"
        uses: actions/checkout@v1
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - name: "Print result"
        run: |
          echo "upload_url: ${{ steps.last_release.outputs.upload_url }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
      - name: Build Carthage
        run: |
          ./scripts/carthage.sh
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.last_release.outputs.upload_url }}
          asset_path: ./Mixpanel.framework.zip
          asset_name: Mixpanel.framework.zip
          asset_content_type: application/zip
